// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfIAHuFHD2_gl71s28PyoCMWtjncAlw7Y',
    appId: '1:994425544757:web:a56254f278fbb5d87dd17c',
    messagingSenderId: '994425544757',
    projectId: 'cebr-704d0',
    databaseURL: 'https://cebr-704d0-default-rtdb.firebaseio.com/',
    authDomain: 'cebr-704d0.firebaseapp.com',
    storageBucket: 'cebr-704d0.appspot.com',
    measurementId: 'G-GX16B0TMQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KhyG1t0mniH9Qp2G6-3h9sJeMQHZuBo',
    appId: '1:994425544757:android:b180650079a12f247dd17c',
    messagingSenderId: '994425544757',
    databaseURL: 'https://cebr-704d0-default-rtdb.firebaseio.com/',
    projectId: 'cebr-704d0',
    storageBucket: 'cebr-704d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAUwlGvomiacq_1cYyv_Ll9UutzMG6TeA',
    appId: '1:994425544757:ios:fe9a840a6ee9929b7dd17c',
    messagingSenderId: '994425544757',
    projectId: 'cebr-704d0',
    databaseURL: 'https://cebr-704d0-default-rtdb.firebaseio.com/',
    storageBucket: 'cebr-704d0.appspot.com',
    iosClientId: '994425544757-p07udis0gaqhk0gelhok7sdrvmfq2han.apps.googleusercontent.com',
    iosBundleId: 'com.example.cebr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAUwlGvomiacq_1cYyv_Ll9UutzMG6TeA',
    appId: '1:994425544757:ios:fe9a840a6ee9929b7dd17c',
    messagingSenderId: '994425544757',
    projectId: 'cebr-704d0',
    databaseURL: 'https://cebr-704d0-default-rtdb.firebaseio.com/',
    storageBucket: 'cebr-704d0.appspot.com',
    iosClientId: '994425544757-p07udis0gaqhk0gelhok7sdrvmfq2han.apps.googleusercontent.com',
    iosBundleId: 'com.example.cebr',
  );
}
